version: '3'
services:
  senko-web:
    build: ./senko-web
    # localで使いたいportに適宜変える
    ports:
      - "9999:80"
    links:
      - senko-app
    volumes:
      - ./senko-app/project:/project
  senko-app:
    tty: true
    build:
      context: ./senko-app
    ports:
      - "5000:5000"
    volumes:
      - ./senko-app/project:/project
