swagger: "2.0"
info:
  description: "書類選考自動化API"
  version: "0.0.1"
  title: "senko"
  contact:
    email: "eguchi@asial.co.jp"
host: "senko-asial.com"
basePath: "/apiv1/"
tags:
- name: "person"
  description: "応募者"
schemes:
- "https"
paths:
  /person:
    post:
      tags:
      - "person"
      summary: "応募者登録"
      description: "応募者の新規登録"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Person"
      responses:
        201:
          description: "person created."
        400:
          description: "Invalid ID supplied"
  /person/list:
    get:
      tags:
      - "person"
      summary: "応募者一覧取得"
      description: "応募者一覧取得 ページ指定 件数指定"
      produces:
      - "application/json"
      parameters:
      - name: "limit"
        in: "query"
        description: "取得件数"
        required: false
        type: "integer"
        default: 20
      - name: "page"
        in: "query"
        description: "ページ"
        required: false
        type: "integer"
        default: 1
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Person"
        400:
          description: "Invalid tag value"
  /person/list/search/{word}:
    get:
      tags:
      - "person"
      summary: "応募者フリーワード検索"
      description: "応募者一覧取得 部分一致検索"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: "word"
        description: "検索文字列"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Person"
        400:
          description: "Invalid tag value"
definitions:
  Person:
    type: "object"
    required:
    - "name"
    - "address"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "田中 太郎"
      photoUrl:
        type: "string"
        example: "http://hogegoge/pic/111"
      status:
        type: "string"
        description: "選考ステータス"
        enum:
        - "new"
        - "pending"
        - "thinking0"
        - "thinking1"
        - "thinking2"
        - "ok"
        - "ng"
    xml:
      name: "Pet"